### ISSUE TITLE
老哥，数据库没有初始化啊

### ISSUE THREAD

**Issue by aohanhongzhi** [olongfen/gorm-gin-admin#2]
好不容易弄好了登录，一进去傻眼了。数据库没有初始化，菜单看不到，直接404了。

![](https://ftp.bmp.ovh/imgs/2020/09/9fd0dd86c23cc143.png)

**Comment by lefinx** [comment]
菜单是动态路由，得先去数据库设置一个主菜单才行，你去看我线上demo的数据，导出来存进数据库，我后面会在开发完成后后端初始化时自动生成基本菜单路由的

**Comment by aohanhongzhi** [comment]
@olongfen 老哥加个QQ。麻烦数据库表导出来，我好好学习下。老哥，非常感谢。

**Comment by aohanhongzhi** [comment]
@olongfen 3227556776

**Comment by lefinx** [comment]
你拉一下前端代码，我刚刚加了一个静态路由，就是后端没有动态路由的话自动走静态路由
